openapi: 3.0.2
info:
  version: 1.0.0
  title: Asychronous Client API
  contact:
    email: engineer.anthony.ng@gmail.com
  
  x-logo:
    url: 'https://www.wonderbill.com/images/Logoheader.png'
  description: >

    # Introduction

    This [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md) Specification describe the endpoints of the Asynchronous Client micro-service.

tags:
  - name: Datahog
    description: Datahog retrieval request
servers:
  - url: 'http://localhost:3100/api/v1'
  - url: 'https://localhost:3100/api/v1'
paths:
  '/requests/{requestId}':
    $ref: 'paths/requests@{requestId}.yaml'
  '/callbacks/{requestId}':
    $ref: 'paths/callbacks@{requestId}.yaml'
